### ISSUE TITLE
Support https for ingress-nginx

### ISSUE THREAD

**Issue by upgradingdave** [camunda-community-hub/camunda-8-helm-profiles#14]
Currently the links inside this [ingress-nginx values file](https://github.com/camunda-community-hub/camunda-8-helm-profiles/blob/master/ingress-nginx/camunda-values.yaml) are set to `http`. 

There's currently no automatic way to change those links from http to https. It's possible to manually change then, but it would be nice to have an option (maybe in the makefile?) to use https links.

**Comment by aabouzaid** [comment]
I think that could be happen at the same step when the public IP address is added to the values file.

**Comment by falko** [comment]
May be fixed by @rob2universe via #31

**Comment by rob2universe** [comment]
I think we discussed that we want the host to become a parameter of the ootb camunda chart. I would also add a switch for enabling tls secret and name. Then the chart could automatically set the correctly protocol and enable tls on the ingress', as well as set the tls secret name.

**Comment by upgradingdave** [comment]
`https` is now supported, and the default, in #36.
