### ISSUE TITLE
sed command to replace ip addresses fails on linux

### ISSUE THREAD

**Issue by upgradingdave** [camunda-community-hub/camunda-8-helm-profiles#15]
This sed syntax doesn't work on Linux (Gnu sed)

https://github.com/camunda-community-hub/camunda-8-helm-profiles/blob/f083299faef259d21a6fd20c630a1163c1b7a8a2/include/ingress-nginx.mk#L22

```
sed -Ei ''
```
[ingress-nginx.mk](https://github.com/camunda-community-hub/camunda-8-helm-profiles/blob/f083299faef259d21a6fd20c630a1163c1b7a8a2/include/ingress-nginx.mk)

```
sed -Ei '' "s/([0-9]{1,3}\.){3}[0-9]{1,3}/$$IP/g" camunda-values.yaml ; \
```

Not sure if there is a compatible way to make it (e.g. if just removing the quotes '' or it's mandatory in mac)
the pipeline way will make it

```
cat camunda-values.yaml | sed -E "s/([0-9]{1,3}\.){3}[0-9]{1,3}/$$IP/g" > camunda-values-updated.yaml
```

**Comment by falko** [comment]
Maybe we should get rid of `sed` completely, e.g. by passing URLs as separate values directly to Helm.

**Comment by upgradingdave** [comment]
I'm working on this in the `ipaddress` [branch](https://github.com/camunda-community-hub/camunda-8-helm-profiles/tree/ipaddress). 

- Azure should work now on both linux and mac
- When installing azure ingress, the ip address is automatically configured (no longer needed to enter in the command line)

I haven't implemented for AWS yet, but will try to do so soon. 

Note that I tried to use helm `--post-renderer`, but running into an issue. The `post-renderer.sh` script needs the values of make variables to be useful. For example, `az` command needs `$(nodeResourceGroup)` and `$(appGatewayName)` in order to find the ip address to use. But, so far, I haven't found a solution that I'm happy with to access makefile variables inside the `post-renderer.sh script`?

**Comment by falko** [comment]
Maybe we could generate the post render script as a temporary file. But I guess that's similar to generating the yaml file with sed.

Did you try if environment variables make it though to the post render script similar to what we did in the update target?

**Comment by upgradingdave** [comment]
Hi Falko, I like the idea of using environment variables + render scripts. That might work, however I think it'll be a fairly significant refactor, so I'm going to open a separate github issue for refactoring to use post render scripts.

Meanwhile, the latest code in the `ipaddress` branch is able to automatically find IP addresses and should work on mac and linux for AWS and Azure. Next step is to test to make sure auto discovering ip address in Google still works.

**Comment by upgradingdave** [comment]
I heard a report of the following issue today. This is on Mac osx Monterey: 

[ingress-aws.mk](http://ingress-aws.mk/) attempts to get the IP address from the cluster. For some reason, sometimes when the targets from this file are run, the `$(IP)` variable appears to be set correctly in the `elb-ip-address` target but then it’s not set in the `camunda-values-aws.yaml` target?

Here's an example output showing the issue: 

```
./aws-ingress.sh
Attempt to find ip address ...
Found ip address: 18.158.81.183
Attempting to configure ingress with IP Address 
sed "s/127.0.0.1//g;" ../ingress-nginx/camunda-values.yaml > ./camunda-values-aws.yaml
```

So far, I'm not able to reproduce this behavior, but need to research to see if maybe the way this `IP` variable is geting set inside the Makefile can be improved?

**Comment by upgradingdave** [comment]
Scripts have been working on mac and linux for a while now, I haven't heard of any recent complaints. 

Also - as long as Windows folks use the Windows Linux Subsystem these scripts should work as is. 

Closing this issue for now. If we decide later to replace `sed` we can tackle that elsewhere.
