### ISSUE TITLE
Add configuration to allow C8 client to communicate via gRPC from outside the cluster

### ISSUE THREAD

**Issue by plungu** [camunda-community-hub/camunda-8-helm-profiles#19]

**Comment by superbeagle** [comment]
This does come up on a regular basis with prospect and customers (FEMA and Johnson and Johnson this past week)

**Comment by upgradingdave** [comment]
The `nginx/ingress/tls` profiles for AWS, Azure and Google all configure an endpoint to communicate with Zeebe GRPC by default. 

There is also this [azure secure zeebe ingress](https://github.com/rob2universe/camunda-8-helm-profiles/tree/azure-secure-ingress/azure/ingress/nginx/tls/secure-zeebe-ingress) profile that is currently in the works which demonstrates how to secure the zeebe gatway using an Oauth 2 server and Keycloak.
