### ISSUE TITLE
Disable ingress creation in values file

### ISSUE THREAD

**Issue by igorinsky** [camunda-community-hub/camunda-8-helm-profiles#2]
Hello,
I'd like to use my own ingress configuration together with zeebe/zeebe-full deployed with dev profile from here.
 
Is there a way to disable/configure ingress creation in value files so I don't have to disable it every helm upgrade?

**Comment by salaboy** [comment]
@igorinsky any reason not to go with the independent charts? If you want your own ingress probably you want to own your `full` chart and copy the bits that you need. The full chart depends on the `zeebe-cluster` and `zeebe-operate` charts that you can reuse. 
Another option is to contribute with those flags for the full chart. I would recommend creating the issue in the right repo for that.

**Comment by salaboy** [comment]
@igorinsky let me know if you want/need mentoring on how to do that, I am happy to guide and help to implement the change.

**Comment by falko** [comment]
The new Camunda Platform 8 Helm Chart allows this.
