### ISSUE TITLE
Make fails when run in default and development

### ISSUE THREAD

**Issue by barmac** [camunda-community-hub/camunda-8-helm-profiles#28]
Recent change of `camunda.mk` broke the setup for `default` and `development` configs. More in the comment: https://github.com/camunda-community-hub/camunda-8-helm-profiles/commit/d4684caee2f12f0e1fc834b785769e6cfff835aa#r86790359

**Comment by upgradingdave** [comment]
Finally got around to fixing the relative paths for the two directories, thanks for reporting this, @barmac!
