### ISSUE TITLE
Replace rebalance-leaders with k8s job

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/camunda-8-helm-profiles#46]
see: https://github.com/zeebe-io/benchmark-helm/pull/7 and `deploy-models` in https://github.com/camunda-consulting/zeebe-tuner/blob/master/src/main/resources/benchmarktemplates/Makefile

**Comment by falko** [comment]
@upgradingdave would you like to take this on given that you worked on #62 already?

**Comment by upgradingdave** [comment]
Hi @falko, yes, I could look into this. I'll block some time to work on this on Friday and will update status here 👍

**Comment by falko** [comment]
This is really an impediment for any benchmarks now because the `rebalance-leaders` in the main branch is broken for Zeebe 8.2.11 and onwards. Zeebe Tuner requires this to work. As a workaround, I'm working with the old code, which we should restore if we don't get the job to work, soon.

**Comment by upgradingdave** [comment]
Hi @falko, I used [this example](https://github.com/zeebe-io/benchmark-helm/pull/7) to create a job that uses a curl image to rebalance leaders. See commit 63ee2cc6bc82b9b860fe6521c1fc785f88429d8e
