### ISSUE TITLE
Camunda chart version hard coded

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/camunda-8-helm-profiles#57]
@upgradingdave was there a particular reason for hard-coding the Helm chart version, especially give that we are fetching the latest chart in the line before? 

https://github.com/camunda-community-hub/camunda-8-helm-profiles/blob/e9f81e1f4c6f028e668738e812c3e970f148eb51/include/camunda.mk#L7C91-L7C91

Note that this `--version` flag is not the Camunda version to be installed.

**Comment by falko** [comment]
@upgradingdave any opinion on this. If not, I will remove the version number

**Comment by upgradingdave** [comment]
Hi @falko, yes please feel free to remove that version. I added that version number when I was testing a specific version of helm charts and didn't mean to commit. Thanks!

**Comment by upgradingdave** [comment]
I just realized that I actually already removed in [this commit](https://github.com/camunda-community-hub/camunda-8-helm-profiles/commit/a3629b9180827c63fed0a30d5739ffaa75995b71). This should be good now 👍
